openapi: 3.0.0
info:
  title: Playola API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.2.0

paths:
  # For now, OpenAPI does not support importing an entire file of path
  # definitions.  So, each path must be defined and referenced.

  # --- Spotify ---
  /v1/spotify/auth/authorize:
    $ref: './spotify.swagger.yaml/#/SpotifyAuthorizeEndpoint'

  /v1/spotify/auth/token/swap:
    $ref: './spotify.swagger.yaml/#/SpotifyAuthTokenSwapEndpoint'
    
  # --- Users ---
  /v1/users:
    $ref: './user.swagger.yaml/#/CreateUserEndpoint'